### ISSUE TITLE
pkg-config isn't listed as a dependency

### ISSUE THREAD

**Issue by Ichimonji10** [w3c-validators/w3c_validators#30]
Executing the sample code from the readme produces a traceback if pkg-config isn't installed. pkg-config isn't listed as a dependency, at least on this package's [rubygems page](https://rubygems.org/gems/w3c_validators).

**Comment by doc75** [comment]
Hello,

I am working on Linux and I cannot see any traceback.
Could you please provide some more information ?
- which example of the Readme are you using (as they are several examples) ?
- Please provide the traceback you have on your side.
- Please precise the OS you are using.
Thanks.

**Comment by Ichimonji10** [comment]
I'm using the readme from the current master branch. Specifically, here's the script I'm executing:

```ruby
#!/usr/bin/env ruby
# Taken from the readme. Run this script after updates as a sanity check.
require 'w3c_validators'

include W3CValidators

@validator = CSSValidator.new

results = @validator.validate_text('body { margin: 0px; }')

if results.errors.length > 0
  results.errors.each do |err|
    puts err.to_s
  end
else
  puts 'Valid!'
end
```

Here's the traceback:

```console
$ ./test.rb 
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'pkg-config' (~> 1.1.7) among 22 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/ichimonji10/.gem/ruby/2.3.0:/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from ./test.rb:3:in `<main>'
$ sudo pacman -S --asdeps ruby-pkg-config
[snip!]
$ ./test.rb 
Valid!
```

I'm using Arch Linux.

I'm brainstorming for other possible issues. One other explanation is that some *other* gem requires pkg-config, and that other gem isn't properly packaged.

**Comment by doc75** [comment]
@Ichimonji10 Thanks for the additional information.

I tested on Ubuntu 16.04 (I have no Arch Linux indeed) with [rvm](https://rvm.io/).
```console
$ rvm use 2.2@test --create
ruby-2.2.5 - #gemset created /home/user/.rvm/gems/ruby-2.2.5@test
ruby-2.2.5 - #generating test wrappers..........
Using /home/user/.rvm/gems/ruby-2.2.5 with gemset test

$ gem install w3c_validators
Fetching: json-2.0.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-2.0.2
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.7.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.7.0
Fetching: w3c_validators-1.3.1.gem (100%)
Successfully installed w3c_validators-1.3.1
4 gems installed

$ ./test.rb 
Valid!
```

I cannot see the issue you are mentioning.

- Are you using ruby 2.0 at least ?
- Are you sure the version of the gem are the correct one ? Indeed, when using the one from your package manager, they can be older than they should.

Let me know if you sort this out.
 and which is probably linked to either the wrong gem version used

**Comment by Ichimonji10** [comment]
> Are you using ruby 2.0 at least ?

I'm using ruby 2.3.0:

```console
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/ichimonji10/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/ichimonji10/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/2.3.0
     - /home/ichimonji10/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /usr/lib/jvm/default/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl
```

> Are you sure the version of the gem are the correct one ? Indeed, when using the one from your package manager, they can be older than they should.

I think this is the issue. The [ruby-nokogiri AUR package](https://aur.archlinux.org/packages/ruby-nokogiri/) is currently at version 1.6.8. Also, the [1.6.8.1 changelog](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#1681--2016-10-03) describes how pkg-config was made a dependency in version 1.6.8 and then made an optional dependency in 1.6.8.1.

Also, `gem`'s output fits neatly with this theory:

```console
$ gem dependency -R pkg-config
Gem pkg-config-1.1.7
  bundler (>= 0, development)
  rake (>= 0, development)
  test-unit (>= 0, development)
  Used by
    nokogiri-1.6.8 (pkg-config (~> 1.1.7))
```

I'm tentatively closing this bug. Thank you for your help, @doc75!

**Comment by doc75** [comment]
@lchimonji10 I am glad you figure it out.
Thanks for closing it.
